### ISSUE TITLE
Windows32 Support

### ISSUE THREAD

**Issue by shubhtuls** [dfouhey/caffe64#1]
Hi,
Thanks for the great resource. Unfortunately, this is not compatible with my current computing setup. Do you plan on adding support for 32bit Windows anytime soon in the future?

**Comment by dfouhey** [comment]
Super duper easy. Why don't you just:
* replace all the references to rax/rbx/rcx to eax/ebx/ecx etc
* switch the system calls to the corresponding interrupts (int 0x80), including changing the calling convention to whatever windows uses
* remove all references to r8-r15 (including rewriting any procedures that use them). You might have to use the stack a bit more since the current code bends over backwards to avoid local variables since I'm bad at keeping track of them
* redo the entry point at _start to whatever windows does since this is an ELF binary
* replace all the sse floating point code with 8087 fpu floating point code if you don't have a processor with SSE

Best of luck! Send me your fork if it works!
