### ISSUE TITLE
please produce a library version

### ISSUE THREAD

**Issue by aaalgo** [dfouhey/caffe64#3]
This is the most beautiful thing I've seen in years and I think it's almost close to zen.
I just found the original Caffe has added a bunch of dependencies and it almost killed me to rebuild a bunch of programs I wrote about a year ago.  I only wish you have a library version that can be linked to my program.

Nice job!

**Comment by aaalgo** [comment]
I played a bit more and I think library is probably not the best way to do it.  I'll be better off just carrying the caffe64 binary.

**Comment by dfouhey** [comment]
Thanks for the feedback. We're glad you have a keen eye for beauty and a distaste for spending tons of time worrying about your linker.

It wouldn't be too crazy to make it a library (although it'd be impossible to multithread right now):
* replace all references to alloc with malloc (they won't play nicely at all) and change the Makefile to not have -nostdlib
* remove _start since that'll definitely confuse stuff
* then write an interface to mainTrain / mainTest. You could probably just pass in (int argc, char **argv) and it'd work.
